name: Wolfram Engine Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04-arm # Use an ARM64 runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install wolfram engine
        shell: bash
        run: |
          chmod +x ./.github/workflows/install.sh
          ./.github/workflows/install.sh
    
      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.19
