name: Wolfram Engine Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04-arm # Use an ARM64 runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: steps
        run: |
            set -eux -o pipefail
            chmod +x ./.github/workflows/install.sh
            WE_MODE=install bash ./.github/workflows/install.sh
            sudo apt install libuv1-dev -y
            sed -i "s@/home/kirill/Downloads/libuv-1.46.0/build/libuv.so@/usr/lib/aarch64-linux-gnu/libuv.so@g" Scripts/BuildLibrary.wls
            sed -i "s@/home/kirill/Downloads/libuv-1.46.0/includes@/usr/include@g" Scripts/BuildLibrary.wls
            sudo echo > "/opt/Wolfram/WolframEngine/14.1/Configuration/Licensing/mathpass" # clear it
            
      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.19
      - name: Build
        run: |
            # I can't figure out how to activate this in ci. So this step will fail.
            /opt/Wolfram/WolframEngine/14.1/SystemFiles/Kernel/Binaries/Linux-ARM64/wolframscript -f Scripts/BuildLibrary.wls
            # after is simple. just release with action
      - name: upload
        uses: actions/upload-artifact@v4
        with:          
              # A file, directory or wildcard pattern that describes what to upload
              # Required.
              path: LibraryResources/
