name: Compile LLink ARM Linux and UV
on: workflow_dispatch
jobs:
  GNULinux-ARM:
    runs-on: ubuntu-24.04-arm
    env:
      WOLFRAM_SYSTEM_ID: Linux-ARM
      WOLFRAMENGINE_CACHE_KEY: WolframEngine-BA
      WOLFRAMENGINE_INSTALLATION_DIRECTORY: "/Applications/Wolfram Engine.app"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Install WE
        run: |
            set -eux -o pipefail
            chmod +x ./.github/workflows/install_arm.sh
            WE_MODE=install bash ./.github/workflows/install_arm.sh
            sudo apt install libuv1-dev -y


      - name: Compile function
        env:
          WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAM_LICENSE_ENTITLEMENT_ID }}
        run: |
          /opt/Wolfram/WolframEngine/14.1/SystemFiles/Kernel/Binaries/Linux-ARM64/wolframscript -debug -verbose -script ./Scripts/BuildLibrary.wls /usr/include /usr/lib/aarch64-linux-gnu/libuv.so


      - name: Commit files
        run: |
          git config pull.rebase true
          get fetch
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add LibraryResources/
          git commit -m "Add binary for ${{ env.WOLFRAM_SYSTEM_ID }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}