name: Compile LLink x86 Linux 
on: workflow_dispatch
jobs:
  Linux-x86-64-v8:
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:14.2
      options: --user root
    env:
      WOLFRAM_SYSTEM_ID: Linux-x86-64-v8
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}        

      - name: Install build tools
        run: |
          apt-get -y update
          apt-get -y install build-essential

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Compile function
        env:
          WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAM_LICENSE_ENTITLEMENT_ID }}
        run: |
          wolframscript -script ./compile.wls
