name: Compile LLink x86 Linux 
on: workflow_dispatch
jobs:
  Linux-x86-64-v8:
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:14.2
      options: --user root
    env:
      WOLFRAM_SYSTEM_ID: Linux-x86-64-v8
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}        

      - name: Install build tools
        run: |
          apt-get -y update
          apt-get -y install build-essential
          apt-get -y install libuv1-dev
          apt-get -y install git

      - name: Debug Workspace
        run: |
          echo "Current directory: $(pwd)"
          echo "GitHub workspace: $GITHUB_WORKSPACE"
          ls -la $GITHUB_WORKSPACE

      - name: Compile function
        env:
          WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAM_LICENSE_ENTITLEMENT_ID }}
        run: |
          cd $GITHUB_WORKSPACE  # Make sure we are in the repo
          wolframscript -script ./Scripts/BuildLibrary.wls /usr/include/ /usr/lib/x86_64-linux-gnu/libuv.so

      - name: Commit files
        run: |
          cd $GITHUB_WORKSPACE  # Ensure we are inside the Git repo
          git config pull.rebase true
          git fetch        
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add LibraryResources/
          git commit -m "Add binary for ${{ env.WOLFRAM_SYSTEM_ID }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}


  Linux-x86-64-v7:
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:14.1
      options: --user root

    env:
      WOLFRAM_SYSTEM_ID: Linux-x86-64-v7
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}        

      - name: Install build tools
        run: |
          apt-get -y update
          apt-get -y install build-essential
          apt-get -y install libuv1-dev
          apt-get -y install git

      - name: Debug Workspace
        run: |
          echo "Current directory: $(pwd)"
          echo "GitHub workspace: $GITHUB_WORKSPACE"
          ls -la $GITHUB_WORKSPACE

      - name: Compile function
        env:
          WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAM_LICENSE_ENTITLEMENT_ID }}
        run: |
          cd $GITHUB_WORKSPACE  # Make sure we are in the repo
          wolframscript -script ./Scripts/BuildLibrary.wls /usr/include/ /usr/lib/x86_64-linux-gnu/libuv.so

      - name: Commit files
        run: |
          cd $GITHUB_WORKSPACE  # Ensure we are inside the Git repo
          git config pull.rebase true
          git fetch        
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add LibraryResources/
          git commit -m "Add binary for ${{ env.WOLFRAM_SYSTEM_ID }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}