name: Compile LLink ARM Linux and UV
on: workflow_dispatch
jobs:
  FunctionCompile-GNULinux-ARM:
    runs-on: ubuntu-24.04-arm
    env:
      WOLFRAM_SYSTEM_ID: Linux-ARM
      WOLFRAMENGINE_CACHE_KEY: WolframEngine-BA
      WOLFRAMENGINE_INSTALLATION_DIRECTORY: "/Applications/Wolfram Engine.app"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install WE
        run: |
            set -eux -o pipefail
            chmod +x ./.github/workflows/install_arm.sh
            WE_MODE=install bash ./.github/workflows/install_arm.sh
            sudo apt install libuv1-dev -y


      - name: Compile function
        env:
          WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAM_LICENSE_ENTITLEMENT_ID }}
        run: |
          /opt/Wolfram/WolframEngine/14.1/SystemFiles/Kernel/Binaries/Linux-ARM64/wolframscript -debug -verbose -script ./Scripts/BuildLibrary.wls /usr/include /usr/lib/aarch64-linux-gnu/libuv.so


      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add LibraryResources/
          git commit -m "Add compiled function libraries for ${{ env.WOLFRAM_SYSTEM_ID }}"
          git push origin main  # Change branch if necessary